### ISSUE TITLE
Drop the `api` namespace from routes

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#16]
We have an unnecessary `api` namespace, leading to weird URLs such as `https://api.example.com/api/v1/stuff`.

In the beginning we were running the API and client on the same domain. While it made sense back then, now we are running separate hosts for each and this is likely going to be the default setup from now on.

If you wish, this can be extracted into some optional behaviour, although I can't see any point in doing it now.

Thanks! 🙃

**Comment by victor-nitu** [comment]
Leaving this open to keep in mind for the upcoming refactoring. Just saying, so we don't close it :)

**Comment by georgiana-b** [comment]
I'll close this too keep all namespace discussion in #39
