### ISSUE TITLE
Update network graph

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#25]
Currently we can't send back altered versions of the graph. This is needed for custom made networks, as well as for unblocking:

 - tenders-exposed/elvis-ember#74 Save a modified graph to the network
 - tenders-exposed/elvis-ember#83 Save manually made clusters

We should be able to update the `graph` of a network in the following ways:
- [ ] delete nodes
- [ ] add nodes
- [ ] update existing nodes attributes

**Comment by georgiana-b** [comment]
This issue was moved to tenders-exposed/elvis-backend-py#16
