### ISSUE TITLE
Missing the 72.. CPV from the Dutch data

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-backend#27]
It is definitely there. Where did it go?

**Comment by georgiana-b** [comment]
It sure is, as shown by this request for all the CPV's in NL contracts (see 2'nd result 👇 ) along with all it's children and grandchildren which didn't make the photo. 

![72_cpv](https://cloud.githubusercontent.com/assets/8862002/21284841/56c3b580-c430-11e6-9272-749ea7b68253.png)

@zufanka You can't see it in the front-end?

**Comment by zufanka** [comment]
it has to do [with this one!](https://github.com/tenders-exposed/elvis-ember/issues/106) frontend problem :) sorry!

**Comment by georgiana-b** [comment]
No problem!
