### ISSUE TITLE
Cannot get a supplier's details

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#28]
Given the following HTTP request:

```
POST /api/v1/contracts/suppliers_details HTTP/1.1
Host: api.elvis.tenders.exposed
Content-Type: application/json
X-User-Email: email@example.com
X-User-Token: tokenblahblah
Cache-Control: no-cache

{
	"query": {
		"suppliers": [538852]
	}
}
```

The response is a JSON as follows:

>
> {
>  "error": "\nmessage:\n  Document not found for class Contract with attributes {:\"suppliers.x_slug_id\"=>538852}.\nsummary:\n  When calling Contract.find_by with a hash of attributes, all attributes provided must match a document in the database or this error will be raised.\nresolution:\n  Search for attributes that are in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error."
> }

Ideally, this would return a supplier's details selected by its `x_slug_id`.

**Comment by georgiana-b** [comment]
@nightsh I think this problem was caused by ES index being out of date. I updated the index now so this should be solved. Feel free to reopen if it's not.
