### ISSUE TITLE
Allow case insensitive country codes

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#3]
Right now, the countries parameter (array) only allows `[A-Z]{2,2}`.

It would make sense to change it to `[A-Za-z]{2,2}` and make it uppercase upon receiving it.

Cheers! :beers:

**Comment by georgiana-b** [comment]
Currently country names respect _ISO 3166-1 alpha-2_ standard which makes them easy to understand and use. I think making them case insensitive would make things less clear and thus wouldn't be an enhancement.

**Comment by victor-nitu** [comment]
:heart:  standards!
