### ISSUE TITLE
New feature to save a thumbnail for a generated network

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#31]
We need to show thumbnails for networks, but we need a way to send them to the API.

Options:

1. Generate the image client side, upload it to a 3rd party and send the link to the API (a bit insecure)
2. Generate the image client side, `PUT` it on an API route, then get back the link to it.
3. Same as 2, but instead of making the images available through a link, send them as blobs with the appropriate `Content-Type` (my fav so far).

@georgiana-b can we have a complexity estimate for this?

**Comment by zufanka** [comment]
@georgiana-b @nightsh also something for when the new backend is ready?

**Comment by georgiana-b** [comment]
This issue was moved to tenders-exposed/elvis-backend-py#17
