### ISSUE TITLE
Feature to store performance indicators

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#32]
The idea is to store some performance indicators for API clients using the Elvis frontend. Structure of a measurement should be as follows.

Obvious hint: values sampled as empty strings `''` are typed as strings, values given as `0` are integers.

```js
{
  version: '',    // frontend version
  created_at: '', // measurement timestamp

  network: {
    id: '',       // ID of the network
    contracts: 0, // contracts count (obtained in CPV selector)
    nodes: 0,     // number of nodes
    edges: 0,     // number of edges
  },

  client: {
    os: {
      name: '',   // e.g. 'Linux'
      version: '' // e.g. '4.9.1'
    },
    browser: {
      name: '',   // e.g. 'Chrome'
      version: '' // e.g.'50'
    },
    resolution: {
      screen: '', // e.g. '1920x1080'
      window: '', // e.g. '1000x600'
    },
    device: {
      type: '',   // e.g. 'Smartphone'
      name: ''    // e.g. 'iThing'
    },
    misc: '',     // Serialized object (JSON) with misc data, if needed
  },

  performance: {
    cpvs: {
      count: 0,      // CPVs count
      loadTime: 0,   // time between CPV request and response
      treeRender: 0, // time to render the CPV tree
    },
    network: {
      save: 0,            // time between network request and response
      iterationsTime: 0,  // time to stabilize
      iterationsCount: 0, // iterations to stabilize
      renderTime: 0,      // time to render (whether stabilized or not)
    }
  }
}
```

**Comment by victor-nitu** [comment]
If it's easier, we could just use the API to forward the request to a 3rd party, say Google Docs. Thus, a user could send a payload to a forwarder route (say, `/google`), and the API would use an API token against their service to send a payload into a spreadsheet. This would spare us from the burden of having to create special logic for this potentially temporary feature.

To put it simply: only use Rails to forward the payload to a GDocs spreadsheet. Can't do it on the client side, because we wouldn't want to expose the auth/token details.

WDYT @georgiana-b?

**Comment by georgiana-b** [comment]
@nightsh I made an endpoint to save performance indicators. 

POST `api/v1/performance_stats` with the payload you gave above wrapped in a "performance_stats" object:

```json
{
    "performance_stats": {
        "version": "",
        "created_at": "",
       [...]
    }
}
```
To make sure the endpoint won't be abused, it required authentication. Let me know if you need any further help on this.
