### ISSUE TITLE
Contract IDs are not sent in the contracts payload

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#33]
As the title says, we do receive contracts inside the suppliers payload , for example, but they have no ID. This renders the route to get a contract unusable, since it requires one to function 🙁  

Tasks:

- [ ] Put the ID of the contracts in the payload 🙂

**Comment by georgiana-b** [comment]
@nightsh  Solved in e84366e.  I also fixed the `median` field which was an object instead of a value and renamed it to `median_tenderers` to make it more explicit.
