### ISSUE TITLE
Send multipart emails

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#34]
We need to also send a text version of the email to users, besides the HTML one.

Reason is we get filtered by anti spam mechanisms and sent to junk folders. 
See [the report](http://isnotspam.com/newlatestreport.php?email=ins-6nxs0qvq%40isnotspam.com), all is good except we get this:
> * 3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100%
> * [score: 1.0000]
> * 0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100%
> * [score: 1.0000]

I will test again after the modifications are made, reviewed and merged.

**Comment by victor-nitu** [comment]
Attached some useful files:

* a message as it is received by Gmail: [gmail.txt](https://github.com/tenders-exposed/elvis-backend/files/732294/gmail.txt)
* the isnotspam.com report in text form: [report.txt](https://github.com/tenders-exposed/elvis-backend/files/732295/report.txt)

**Comment by nightsh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backend leftovers](https://trello.com/c/aC1HJEJf/69-backend-leftovers)

**Comment by georgiana-b** [comment]
I added multipart emails in [this commit](https://github.com/tenders-exposed/elvis-backend/commit/d39901c9d24a992a181c02f820a06af21011b2c8) but the emails still end up in spam 😞. @nightsh Let me know if you have any other ideas.
