### ISSUE TITLE
Missing properties from the payload

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#37]
This is a get-them-all issue, in which I will mash together a bunch of unrelated items, which only have one thing in common: they all are missing properties from the API payload. Feel free to split it etc.

- [ ] Networks index (frontend: `/projects`, backend: `/network`)
  - [x] `query`
  - [x] `options`
  - [ ] number of nodes
  - [ ] number of edges

- [x] On network: `description` (also `POST`-able, but I feel this is a separate catch-all issue for missing `POST`s)
- [x] Supplier / Procuring entity: add the date on contracts

**Comment by victor-nitu** [comment]
While you're at procurer/supplier details, maybe you could also have a play with #14?

**Comment by georgiana-b** [comment]
@nightsh, @ca1yps0 

You can already update the following attributes of a network: 

* `name`
* `description`
* `query`
* `options`

Careful with `query` and `options` though because they will cause the network to be regenerated.

**Comment by georgiana-b** [comment]
@nightsh You said

> Supplier / Procuring entity: add the date on contracts

Contracts have several dates (notice publication date, award date, etc) and I'm not sure which one you mean. I assumed you want award date so I added that one but feel free to reopen this if I was wrong.
