### ISSUE TITLE
Decide on the new API namespace

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#39]
This is a crazy small issue, I know. But a lot of things on the operations side depend on whether we replace the `v1` namespace or create a new, shiny `v2`.

I'd advocate for the latter, as we might want to keep two APIs up for a while, for a bunch of various reasons. We can discuss this below, if needed, but it's a discussion I'd rather like happening sooner than later.

**Comment by georgiana-b** [comment]
Agreed. Let's drop `api` as requested in #16 and replace `v1`  with `v2`.

**Comment by georgiana-b** [comment]
This issue was moved to tenders-exposed/elvis-backend-py#19
