### ISSUE TITLE
Fix API unicorn / nginx connection

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#5]
...because right now the socket based reverse proxy is FUBAR.

Also, the current webrick temporary solution is not reliable for deployments, hence Rails has to be manually rebooted.

I'll assign this to myself, to unf*ck it tomorrow AM.

**Comment by victor-nitu** [comment]
The setup I made there is :hankey: 

Can somebody please take a look and properly hook unicorn into nginx / apache?

Right now it's started as blablahost:3000 using temporary webrick connection. It's bad and needs to go...

**Comment by georgiana-b** [comment]
Moved to [Passenger](https://www.phusionpassenger.com/) and things work. I'll close this.
