### ISSUE TITLE
Relationship details

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-backend#54]
Currently we provide `procuring_entities_details` and `suppliers_details` routes where people can receive aggregated data and analysis on different suppliers or procurers.
We also need relationship details as described in tenders-exposed/elvis-ember#201.

In our current backend this would be quite difficult to make because the relationship between 2 entities is not represented as a separate entity and is not stored in the database. This will change when we switch to a graph database and edges will finally be stored.

Our current REST interface also makes it hard to represent relationship details because people can query by suppliers or procurers only in bulk:

```json
{                            
  "query": {
      "countries": ["BE"],
      "cpvs": ["24000000"],
      "years": [ 2008],
      "procuring_entities": [34541],
      "suppliers": [1165518, 1177785],
    }
}
```

So, we have to take this into consideration in the new REST interface and provide a way to query by a relationship.

**Comment by zufanka** [comment]
@georgiana-b is this taken into account in the new backend?

**Comment by georgiana-b** [comment]
This issue was moved to tenders-exposed/elvis-backend-py#13
